### ISSUE TITLE
quest event 메서드 분리 및 구조 통일

### ISSUE THREAD

**Issue by hothuuk** [ht-make/ht-bot#28]
quest event 부분을 보면 코드가 난잡하고 한 메서드에 기능을 다 담아 놔서 코드를 이해하기 힘들다.

각 기능 별로 맞게 메서드를 분리하고 skill event와 같은 형식으로 메서드 구조를 통일하면 좋을 듯 하다.

**Comment by Srude** [comment]
각 이벤트별로 이름변경, request로 분리 하였습니다.
